//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaSaludMain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VidaSaludMain.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my application.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La salud es la ventaja más valiosa que cualquier persona puede tener. Desgraciadamente, mucha 
        ///gente no invierte mucho en su salud hasta que desarrolla un problema de salud serio, tal como un 
        ///ataque cardiaco o cáncer. 
        ///Si usted adopta ahora una forma de vida sana, puede reducir el riesgo de serios problemas de 
        ///salud, aumentar su nivel de energía, sentirse mejor y vivir muchos años más. 
        ///Esta guía personal de la buena salud será uno de sus compañeros en su plan hacia la buena salud. 
        ///Cada semana se i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perder peso si tiene sobrepeso 
        ///(a un paso saludable, de media 
        ///libra a una libra por semana.).
        /// </summary>
        public static string Meta1 {
            get {
                return ResourceManager.GetString("Meta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alimentar tu salud espiritual. Pase 
        ///de 20 a 30 minutos cada día 
        ///desarrollando su espiritualidad: 
        ///estudiando, leyendo, contemplando, 
        ///adorando, orando, o ayudando a alguien 
        ///necesitado.
        /// </summary>
        public static string Meta10 {
            get {
                return ResourceManager.GetString("Meta10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tomar alcohol.
        /// </summary>
        public static string Meta11 {
            get {
                return ResourceManager.GetString("Meta11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comer pasabocas o comida chatarra.
        /// </summary>
        public static string Meta12 {
            get {
                return ResourceManager.GetString("Meta12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comer después de la cena o tres
        ///horas antes de acostarse.
        /// </summary>
        public static string Meta13 {
            get {
                return ResourceManager.GetString("Meta13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dejar de fumar si es fumador..
        /// </summary>
        public static string Meta2 {
            get {
                return ResourceManager.GetString("Meta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cepillar los dientes y pasar el
        ///hilo dental diariamente.
        /// </summary>
        public static string Meta3 {
            get {
                return ResourceManager.GetString("Meta3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comer principalmente granos 
        ///integrales (arroz, pan integral, 
        ///cereales, avena)..
        /// </summary>
        public static string Meta4 {
            get {
                return ResourceManager.GetString("Meta4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomar diariamente de seis a 
        ///ocho vasos de agua..
        /// </summary>
        public static string Meta5 {
            get {
                return ResourceManager.GetString("Meta5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desayunar diariamente.
        /// </summary>
        public static string Meta6 {
            get {
                return ResourceManager.GetString("Meta6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practicar una técnica para reducir 
        ///el estrés, durante por lo menos 
        ///15 a 20 minutos diarios.
        /// </summary>
        public static string Meta7 {
            get {
                return ResourceManager.GetString("Meta7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver televisión no más de una hora 
        ///en día de semana y 2 horas en fines 
        ///de semana, esto con el fin de tener 
        ///más tiempo para la actividad física, 
        ///el descanso adecuado, etc..
        /// </summary>
        public static string Meta8 {
            get {
                return ResourceManager.GetString("Meta8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fomentar una buena red de apoyo, 
        ///dedicar por lo menos de 15 a 20 
        ///minutos de tiempo de calidad cada 
        ///día con un familiar o amigo..
        /// </summary>
        public static string Meta9 {
            get {
                return ResourceManager.GetString("Meta9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.  Esta aplicación está diseñada para que pueda realizar tu proyecto en modalidad de auto estudio, ¿Qué quiere decir esto?, que debe estudiar el material del tema de cada semana y hacer planes de acción con “tu compañero de salud”..
        /// </summary>
        public static string Paso1 {
            get {
                return ResourceManager.GetString("Paso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Selecciona dos metas personales de Buena Salud. Más adelante encontraras una lista de metas personales, que si pones en práctica durante las próximas ocho semanas, mejoraran tu nivel de salud actual, te verás tentado a elegir una actividad que ya estas realizando, pero recuerda que este plan esta diseñado para llevar a cabo nuevas mejoras en tu salud..
        /// </summary>
        public static string Paso2 {
            get {
                return ResourceManager.GetString("Paso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Recluta un “Compañero de Salud”, es más divertido y placentero realizar las actividades en compañía que solo. Tu compañero puede ser tu esposo(a), un hijo o hija,  un amigo o cualquier persona que te pueda ofrecer estímulo y apoyo diariamente al encarar tus desafíos de salud..
        /// </summary>
        public static string Paso3 {
            get {
                return ResourceManager.GetString("Paso3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Comprométete a estudiar el tema de la semana y discute las estrategias con tu compañero de salud para lograr las metas propuestas..
        /// </summary>
        public static string Paso4 {
            get {
                return ResourceManager.GetString("Paso4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Hacer las tareas asignadas, cada semana lee el material de autoestudio, si hay hojas de trabajo llénelas, de esta forma aprenderás a manejar tu salud..
        /// </summary>
        public static string Paso5 {
            get {
                return ResourceManager.GetString("Paso5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Registra tu progreso diariamente. Lleva tu registro personal usando el sistema de puntos de salud que usted acumula por alcanzar sus metas cada día..
        /// </summary>
        public static string Paso6 {
            get {
                return ResourceManager.GetString("Paso6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con esta aplicación   usted   aprenderá en ocho semas  cómo: 
        ///  •   Identificar y desarrollar un estilo de vida sana 
        ///  •   Llegar a ser más activo físicamente 
        ///  •   Escoger alimentos bajos en grasas saturadas y colesterol 
        ///  •   Proteger su salud consumiendo alimentos ricos en fibra 
        ///  •   Lograr y mantener un peso sano 
        ///  •   Reconocer y evitar las dependencias 
        ///  •   Enfrentar más efectivamente el estrés 
        ///  •   Enfocar su atención en la prevención.
        /// </summary>
        public static string Uso {
            get {
                return ResourceManager.GetString("Uso", resourceCulture);
            }
        }
    }
}
